import { MESSENGER_CONNECTION_CARD } from '@/lib/channels/messenger/public-config';
/** Catálogo público: não importa env, crypto nem credenciais. */
export const INTEGRATION_CATALOG = [
 { id: 'webhook', name: 'Signed webhook', icon: 'webhook', description: 'Send selected flow fields to your HTTPS application.', auth: 'api_key', phase: 7, instructions: 'Enter an HTTPS endpoint and a signing secret. Your receiver must verify X-Integration-Signature and deduplicate X-Idempotency-Key. Testing sends synthetic data only.', actions: [{ id: 'send_event', name: 'Send event', fields: ['event', 'value'] }] },
 { id: 'google_sheets', name: 'Google Sheets', icon: 'table', description: 'Read one cell or append a row using your Google account.', auth: 'oauth', phase: 8, instructions: 'Configure the installation Google OAuth app, connect your account and grant spreadsheet access. Read cell requires a single-cell A1 range. Append row uses RAW values: formulas are not evaluated.', actions: [{id:'read_cell',name:'Read cell',fields:['spreadsheet_id','range']},{id:'append_row',name:'Append row',fields:['spreadsheet_id','range','values_json']}] },
 { id:'airtable',name:'Airtable',icon:'table',description:'Read a record field or create a record in a fixed base/table.',auth:'api_key',phase:8,instructions:'Use a personal access token scoped to this base with data.records:read and data.records:write. Enter base and table IDs, not names. Test only reads; writes run only from published flows.',actions:[{id:'read_field',name:'Read record field',fields:['record_id','field']},{id:'create_record',name:'Create record',fields:['fields_json']}]},
 { id:'hubspot',name:'HubSpot',icon:'contacts',description:'Create contacts and deals.',auth:'api_key',phase:9,instructions:'Use a private app token with contact read/write and deal write scopes. Deal actions require the internal pipeline and stage IDs. Test verifies contact read access, not every write scope.',actions:[{id:'create_contact',name:'Create contact',fields:['email','first_name','last_name']},{id:'create_deal',name:'Create deal',fields:['name','pipeline_id','stage_id']}]},
 { id:'stripe',name:'Stripe',icon:'payment',description:'Create payment links and read signed checkout events.',auth:'api_key',phase:9,instructions:'Use a restricted key and endpoint signing secret. Configure the callback shown on your connection for checkout.session.completed and checkout.session.async_payment_succeeded/failed. Only links created by this connection are accepted. Read a specific event ID and field such as payment_status. A created link is NOT payment confirmation; no order is fulfilled automatically.',actions:[{id:'create_payment_link',name:'Create payment link',fields:['price_id','quantity']},{id:'read_received_event',name:'Read verified checkout event',fields:['event_id','field']}]},
 {id:'inbound_webhook',name:'Receive signed events',icon:'webhook',description:'Receive authenticated data and read it in a flow.',auth:'api_key',phase:8,instructions:'Save a signing secret and activate with Test. This validates configuration, not delivery. Send JSON {id,event,data} to the callback with X-Integration-Signature: t=UNIX_SECONDS,v1=HEX_HMAC_SHA256. Sign timestamp + dot + exact body. Timestamp tolerance is five minutes. IDs are unique per connection; reuse with different data is rejected. Read an event by ID in a flow; receiving does not automatically start a bot.',actions:[{id:'read_received_event',name:'Read received event',fields:['event_id','field']}]},
 { id:'slack',name:'Slack',icon:'message',description:'Notify an administrator-selected staff channel.',auth:'api_key',phase:9,instructions:'Use a bot token with chat:write and invite the bot to the staff channel. The destination is fixed in the encrypted connection. Test checks authentication without sending a message.',actions:[{id:'notify_staff',name:'Notify staff',fields:['text']}]},
 { id:'sendgrid',name:'SendGrid',icon:'mail',description:'Send a plain-text notification to a configured staff email.',auth:'api_key',phase:9,instructions:'Use a scoped API key with mail.send and permission to read scopes. Verify the sender in SendGrid. Test checks the key without sending email. This is staff notification, not customer campaigns.',actions:[{id:'notify_staff',name:'Notify staff',fields:['subject','text']}]},
 {id:'custom_api',name:'Custom API',icon:'workflow',description:'Call a fixed HTTPS endpoint and extract one simple result field.',auth:'api_key',phase:8,instructions:'The administrator fixes the endpoint, method and bearer token. Flows cannot change them. Test sends a synthetic event for POST; GET has no body. Response field must be a top-level string, number or boolean.',actions:[{id:'request_value',name:'Request dynamic value',fields:['payload_json','response_field']}]},
 {id:'n8n',name:'n8n',icon:'workflow',description:'Trigger a configured n8n production webhook.',auth:'api_key',phase:8,instructions:'Configure header authentication named X-Webhook-Token in n8n and enter the same secret here. Test sends a synthetic event. Deduplicate the id field in your workflow; uncertain delivery is never resent automatically.',actions:[{id:'trigger_workflow',name:'Trigger automation',fields:['payload_json']}]},
 {id:'zapier',name:'Zapier',icon:'workflow',description:'Send mapped data to a configured Catch Hook.',auth:'api_key',phase:8,instructions:'Create a Catch Hook in Zapier. Keep its URL secret. Test sends a synthetic event. In the Zap, deduplicate the id field before side effects. A successful HTTP response confirms receipt, not completion of all Zap actions.',actions:[{id:'trigger_workflow',name:'Trigger automation',fields:['payload_json']}]},
 {id:'salesforce',name:'Salesforce',icon:'contacts',description:'Create a Contact or Opportunity.',auth:'api_key',phase:9,instructions:'Use your My Domain instance URL and an access token with API access. Rotate/reconnect when the token expires. Opportunity requires your exact stage name and close date. No automatic Salesforce OAuth refresh yet.',actions:[{id:'create_contact',name:'Create contact',fields:['email','first_name','last_name']},{id:'create_opportunity',name:'Create opportunity',fields:['name','stage','close_date']}]},
 {id:'calendly',name:'Calendly',icon:'calendar',description:'Create a single-use scheduling link.',auth:'api_key',phase:9,instructions:'Use a personal access token and an event type ID owned by that account. The result is a booking link, not a confirmed appointment. Customer chooses a slot in Calendly.',actions:[{id:'create_booking_link',name:'Create booking link',fields:[]}]},
 {id:'mailchimp',name:'Mailchimp',icon:'mail',description:'Check audience subscription status without changing consent.',auth:'api_key',phase:9,instructions:'Enter your API key, server prefix and audience ID. The action only reads subscription status; it never subscribes, reactivates or sends a campaign. Test checks audience read access.',actions:[{id:'subscription_status',name:'Read subscription status',fields:['email']}]},
 {id:'dialogflow',name:'Dialogflow ES',icon:'bot',description:'Classify text and return a suggested response.',auth:'api_key',phase:9,instructions:'Enter a Google Cloud OAuth access token and project ID with Dialogflow access. Rotate the short-lived token when it expires. Each execution uses an isolated session; fulfillment is returned, not automatically sent. Test reads the agent configuration.',actions:[{id:'detect_intent',name:'Detect intent',fields:['text','language_code']}]},
 {id:'segment',name:'Segment',icon:'workflow',description:'Send a selected analytics event using an anonymous identifier.',auth:'api_key',phase:9,instructions:'Enter your HTTP source write key. Send only authorized analytics data; never put an email, phone or credential in the anonymous ID or event name. Test ingests a synthetic event and may trigger connected destinations.',actions:[{id:'track_event',name:'Track event',fields:['anonymous_id','event']}]},
 MESSENGER_CONNECTION_CARD,
] as const;
export type PublicConnection = { id: string; provider: string; label: string; revision: number; active: boolean; auth_kind: string; validated_at: string | null; failure_code: string | null };
export type PublicIntegrationRun = { id: string; connection_id: string; action: string; status: string; failure_code: string | null; created_at: string; finished_at: string | null };
export const CONNECTION_COLUMNS = 'id,provider,label,revision,active,auth_kind,validated_at,failure_code';
export const HISTORY_COLUMNS = 'id,connection_id,action,status,failure_code,created_at,finished_at';
export const ACTION_OUTPUTS:Record<string,readonly string[]>={send_event:['accepted'],read_cell:['value'],append_row:['updated_rows'],read_field:['value'],create_record:['id'],create_contact:['id'],create_deal:['id'],create_opportunity:['id'],create_booking_link:['url'],create_payment_link:['id','url'],notify_staff:['id','accepted'],trigger_workflow:['accepted'],request_value:['value'],subscription_status:['status'],detect_intent:['intent','confidence','reply'],track_event:['accepted'],read_received_event:['value']};
